env:
  browser: true
  es6: true

extends:
  - "plugin:react/recommended"
  - "airbnb"
  - "plugin:import/errors"
  - "plugin:import/warnings"

globals:
  # Jest globals.
  describe: "readonly"
  test: "readonly"
  expect: "readonly"

parser: babel-eslint

plugins:
  - "react"
  - "babel"
  - "import"

rules:
  max-len: ["warn", 120]
  camelcase: ["warn"]
  # Ensure there are no default exports.
  import/prefer-default-export: "off"
  import/no-default-export: "error"
  # Configure indent.
  indent: ["error", 4]
  react/jsx-indent: ["error", 4]
  react/jsx-indent-props: ["error", 4]
  # Do not force deconstructing this.props and this.state.
  react/destructuring-assignment: "off"
  # Allow defining defaultProps and propTypes as static public fields.
  react/static-property-placement: ["error", "static getter", {
    "defaultProps": "static public field",
    "displayName": "static public field",
    "propTypes": "static public field",
  }]
  # Ensure semicolons are everywhere.
  babel/semi: ["error", "always"]
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .test.jsx
      moduleDirectory:
        - node_modules
      paths:
        - src
