import React from 'react';
import { PrefixPropTypes } from 'components/metar/renderers/prefix/propTypes';

export const PrefixShort = ({ data: { value } }) => {
    if (value === 'SPECI' || value === 'METAR') {
        return <>Optional prefix prepended to METAR data.</>;
    }

    if (value === 'AUTO') {
        return <>This weather report was generated by automated systems.</>;
    }

    if (value === 'COR') {
        return <>This weather report is a correction of a previous report.</>;
    }

    return null;
};

PrefixShort.propTypes = PrefixPropTypes;
